<a href="https://colab.research.google.com/github/Vedu-Singh/Data-Science/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***NUMPY LIBRARY FOR PYTHON IN DS***

In [1]:
import numpy as np
// check version
print(np.__version__)

SyntaxError: invalid syntax (<ipython-input-1-7c4be2b5e2ec>, line 2)

In [2]:
import numpy as np

# Check version
print(np.__version__)


1.25.2


In [6]:
import numpy as np

# create an array using list in numpy

a = np.array([1,2,3])
print(a)

# to analyse array --> shape method
print(a.shape)               # it will return (3,) which means given array is of 1-dimension with three elements

# to check datatype --> dtype method
print(a.dtype)       # output -> int 64

# to return no. of dimensions --> ndim method
print(a.ndim)      # output -> 1

# to return total number of elements --> size method
print(a.size)       # output -> 3

# to return size in bytes of each element -> itemsize method
print(a.itemsize)   # output -> 8



[1 2 3]
(3,)
int64
1
3
8


In [7]:
# how to acces different element -->
print(a[0])

1


In [8]:
print(a[4])

IndexError: index 4 is out of bounds for axis 0 with size 3

In [9]:
print (a[3])

IndexError: index 3 is out of bounds for axis 0 with size 3

In [10]:
a[2]= 700
print(a)

[  1   2 700]


In [11]:
print (a[2])

700


In [12]:
# mathematical operations --->
b = a*np.array([2,3,6])
print(b)

[   2    6 4200]


In [14]:
# Array vs Python list -->
l = [23,56,78]

m = np.array([23,56,78])

l.append(89)
print(l)

m.append(89)      # numpy object has no attribute -> error
print(m)

[23, 56, 78, 89]


AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [15]:
l = l + [4]

m = m + np.array([4])                     # broadcasting method in numpy
print(l)
print(m)

[23, 56, 78, 89, 4]
[27 60 82]


In [16]:
l = l*2
print(l)

m = m*2
print(m)

[23, 56, 78, 89, 4, 23, 56, 78, 89, 4]
[ 54 120 164]


In [17]:
m = np.sqrt(m)
print(m)

[ 7.34846923 10.95445115 12.80624847]


In [18]:
m = np.log(m)
print(m)

[1.99449202 2.39374587 2.54993321]


**DOT PRODUCT OF VECTORS IN NUMPY**

In [23]:
l1=[1,2,3]
l2=[4,5,6]
# list method -->
n = np.array([1,2,3])

dot=0
for i in range(len(l1)):
  dot += l1[i]*l2[i]
print(dot)


# array method -->

a1 = np.array(l1)
a2 = np.array(l2)

dot = np.dot(a1,a2)
print(dot)


# object method -->
add = a1 * a2
dot = (a1*a2).sum()
# dot = np.sum(add)
print(dot)

# aderate method -->
dot = a1 @ a2
print(dot)

32
32
32
32


In [33]:
# multidimenstional aarays --->

d = np.array([[1,2,3],[4,6,8]])
print(d)
print(d.shape)

print(d[0])
print(d[0][1])
print(d[1][2])
print(d[0,0])

[[1 2 3]
 [4 6 8]]
(2, 3)
[1 2 3]
2
8
1


In [35]:
# slicing --->
print(d[0,:])
print(d[:,0])

# transpose of a multi array -->
print(d.T)

[1 2 3]
[1 4]
[[1 4]
 [2 6]
 [3 8]]


In [36]:
# inverse of an array -->
print(np.linalg.inv(d))

LinAlgError: Last 2 dimensions of the array must be square

In [37]:
d = np.array([[1,2],[4,6]])
print(d)

print(np.linalg.inv(d))

[[1 2]
 [4 6]]
[[-3.   1. ]
 [ 2.  -0.5]]


In [38]:
print(np.linalg.det(d))                   # to calculate determinant

-2.0


In [41]:
# print diagonal matrix

print(np.diag(d))


c = np.diag(d)
print(np.diag(c))

[1 6]
[[1 0]
 [0 6]]


In [44]:
# other operations ---->

n1 = [[1,4,6,8],[5,9,7,2],[56,78,7]]
print(n1)

n3 = np.array([[1,4,6,8],[5,9,7,2],[56,78,26,34]])

print(n3)

print(n3.reshape(4,3))

[[1, 4, 6, 8], [5, 9, 7, 2], [56, 78, 7]]
[[ 1  4  6  8]
 [ 5  9  7  2]
 [56 78 26 34]]
[[ 1  4  6]
 [ 8  5  9]
 [ 7  2 56]
 [78 26 34]]


In [9]:
# indexing --->
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8]])
print(a)

b = a[0,1]
print(b)

# slicing --->

b = a[0,:]              # print all elements of row 0 --> row operation
print(b)

b = a[0,1:3]            # start,end : stop
print(b)

b = a[0:2,1]            # start,end : stop
print(b)

b= a[:,1]          # column operation
print(b)

b = a[-1,1]        # -ve indexing -> last row first column
print(b)

b= a[-1,-1]           # last row and last column
print(b)

b = a[-1,-2]        # -ve indexing -> last row second last column
print(b)

[[1 2 3 4]
 [5 6 7 8]]
2
[1 2 3 4]
[2 3]
[2 6]
[2 6]
6
8
7


In [17]:
# Boolean Indexing ---->
import numpy as np

c = np.array([[1,2],[3,4],[5,6]])        # 2-D matrix {3*2}
print(c)

bool_idx = c > 2
print(bool_idx)

print(c[bool_idx])         # get only those elements where condition is true
print(c[c>2])       # same result

b = np.where(c>2,c,-1)       # where condition is false it will show -1
print(b)

# fancy indexing -->

d = np.array([12,3,4,5,89,56,73,84,32,14])
print(d)

e = [1,3,5]
print(d[e])


# how to print only even numbers from array

even = np.argwhere(d%2==0).flatten()
print(d[even])


[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]
[[-1 -1]
 [ 3  4]
 [ 5  6]]
[12  3  4  5 89 56 73 84 32 14]
[ 3  5 56]
[12  4 56 84 32 14]


In [23]:
# RESHAPING IN NUMPY --->

import numpy as np

f = np.arange(1,7)
print(f)

print(f.shape)           # 1-D with 6 elements

b = f.reshape((2,3))       # 2 -rows and 3-columns with 2-D
print(b)
print(b.shape)

b = f.reshape((3,2))       # 3-rows and 2-columns with 2-D
print(b)
print(b.shape)

# to add new dimension -->

g = f[np.newaxis,:]
print(g)
print(g.shape)

h = f[:,np.newaxis]
print(h)
print(h.shape)

[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2 3 4 5 6]]
(1, 6)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [29]:
# Concatenation in Numpy --->
import numpy as np

a = np.array([[1,2],[3,4]])
print(a)

b = np.array([[5,6]])
print(b)

c = np.concatenate((a,b))
print(c)

c = np.concatenate((a,b), axis=0)      # same result
print(c)

c = np.concatenate((a,b), axis=None)   # just a flatten simple 1-D array
print(c)

c = np.concatenate((a,b), axis=1)
print(c)

[[1 2]
 [3 4]]
[[5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [30]:
c = np.concatenate((a,b.T), axis=1)                     # one more column is added
print(c)

[[1 2 5]
 [3 4 6]]
